version: '3'
services:
  web:
    image: mavidoc/iitlr45v4web:latest
    ports:
      - "80:80"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    restart: always



