version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ec2-user/IITLR45v4dock/IITLR45v4dock:/config.json
    command: --interval 300 --cleanup
    environment:
      - DOCKER_CONFIG=/config.json
    depends_on:
      - web
    restart: always



